import React, { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronRight, Clock3, Film, HelpCircle, MapPin, Play, ShieldCheck, Sparkles, Users, Zap } from 'lucide-react';
import { DRONE_SPECS, FAQ_ITEMS, PORTFOLIO_ITEMS, TEAM_MEMBERS, TESTIMONIALS, PortfolioItem } from '@/data';
import { Navigation, Footer } from '@/components/Navigation';
import ClientNeedsWalkthrough from '@/components/ClientNeedsWalkthrough';
import { VideoModal } from '@/components/VideoModal';
import Seo, { SITE } from '@/components/Seo';
import VideoComparisonSlider from '@/components/VideoComparisonSlider';

const serviceSteps = [
  { n: '01', title: 'Pokalbis ir planas', text: 'Aptariame jūsų norus ir išsigryniname video tikslinę auditoriją' },
  { n: '02', title: 'Filmavimas', text: 'Atvykstame su paruošta technika, baterijų stotele ir aiškiu skrydžio planu.' },
  { n: '03', title: 'Montavimas', text: 'Sumontuojame jūsų video/reelsą' },
  { n: '04', title: 'Rezultatas', text: 'Atsiunčiame jums video' },
];

export default function Home() {
  const [category, setCategory] = useState('all');
  const [video, setVideo] = useState<PortfolioItem | null>(null);
  const [droneId, setDroneId] = useState(DRONE_SPECS[0].id);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const filtered = category === 'all' ? PORTFOLIO_ITEMS.slice(0, 5) : PORTFOLIO_ITEMS.filter(item => item.category === category);
  const drone = DRONE_SPECS.find(item => item.id === droneId) || DRONE_SPECS[0];

  const businessJsonLd = { '@context': 'https://schema.org', '@type': 'ProfessionalService', '@id': `${SITE}/#business`, name: 'Sparnuotis FPV', url: `${SITE}/`, logo: `${SITE}/manus-storage/Sparnuotis-black_99e4bcd7.svg`, description: 'FPV dronų filmavimo ir video gamybos komanda Kaune, Lietuvoje ir Europoje.', email: 'markas@sparnuotis.lt', telephone: '+37068575900', address: { '@type': 'PostalAddress', addressLocality: 'Kaunas', addressCountry: 'LT' }, areaServed: ['Kaunas', 'Vilnius', 'Klaipėda', 'Lithuania', 'Europe'], sameAs: ['https://www.instagram.com/sparnuotisfpv/', 'https://www.tiktok.com/@sparnuotislt', 'https://youtube.com/channel/UCWTB2v7oCzXqE2qiZ2LSpyw/'] };
  return <div className="min-h-screen bg-[#f4f1e9] text-[#27251f]">
    <Seo title="Sparnuotis | FPV dronų filmavimas Kaune, Lietuvoje ir Europoje" description="Sparnuotis kuria profesionalų FPV dronų video Kaune, Lietuvoje ir Europoje: NT, reklamos, renginiai, sportas, Reels ir tiesioginės transliacijos." path="/" jsonLd={businessJsonLd} />
    <Navigation />

    <section className="relative min-h-[720px] flex items-end overflow-hidden bg-[#27251f] text-white">
      <video className="absolute inset-0 w-full h-full object-cover opacity-60" autoPlay muted loop playsInline preload="metadata" poster="/manus-storage/hero-fpv_aaf565b5.jpg" aria-label="FPV drono skrydis">
        <source src="https://sparnuotis.lt/wp-content/uploads/2026/05/Hero2-1.mp4" type="video/mp4" />
      </video>
      <div className="absolute inset-0 hero-shade" />
      <div className="relative z-10 max-w-7xl mx-auto w-full px-5 lg:px-8 pb-20 pt-40"><div className="max-w-4xl">
        <div className="inline-flex items-center gap-2 rounded-full border border-[#efc400]/50 bg-[#27251f]/40 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-[#efc400] mb-6"><span className="w-2 h-2 rounded-full bg-[#efc400]" />FPV kinematografija Kaune ir visoje Lietuvoje</div>
        <h1 className="font-display text-5xl sm:text-7xl lg:text-8xl leading-[.95] tracking-[-.05em] font-bold mb-7">Filmuojame.<br /><span className="text-[#efc400]">FPV dronais</span></h1>
        <p className="text-lg sm:text-xl text-white/80 max-w-2xl leading-relaxed mb-9">Nuo filmavimo 160 km/h greičiu paskui automobilį iki ramaus praskridimo pro kavinės duris.</p>
        <div className="flex flex-wrap gap-3"><a href="#poreikiu-vedlys" className="rounded-full bg-[#efc400] text-[#27251f] px-6 py-3.5 font-bold hover:bg-[#ffd72f] transition-colors">Sužinoti projekto kainą <ArrowRight className="inline w-4 h-4 ml-1" /></a><a href="#portfolio" className="rounded-full border border-white/35 bg-white/10 px-6 py-3.5 font-semibold hover:bg-white/15 transition-colors"><Play className="inline w-4 h-4 mr-2 fill-[#efc400] text-[#efc400]" />Peržiūrėti darbus</a></div>
        <div className="flex flex-wrap gap-x-8 gap-y-3 mt-12 text-sm text-white/75"><span><ShieldCheck className="inline w-4 h-4 text-[#efc400] mr-2" />Saugūs skrydžiai patalpose</span><span><Clock3 className="inline w-4 h-4 text-[#efc400] mr-2" />Kaina valandiniu arba už visą projektą</span><span><MapPin className="inline w-4 h-4 text-[#efc400] mr-2" />Kaunas, visa Lietuva</span></div>
      </div></div>
    </section>

    <section id="filosofija" className="py-20 md:py-28 paper-grid"><div className="max-w-7xl mx-auto px-5 lg:px-8 grid lg:grid-cols-12 gap-12 items-center"><div className="lg:col-span-6"><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Mūsų mąstymas</div><h2 className="font-display text-4xl sm:text-5xl font-bold leading-[1.02] tracking-tight">Kodėl tradicinio drono nebeužtenka?</h2><div className="mt-7 space-y-4 text-[#6d6a61] leading-relaxed"><p>Dauguma dronų pakyla aukštai ir gražiai parodo vaizdą. FPV daro kitą dalyką: leidžia žiūrovui pajusti greitį, aukštį ir artumą.</p><p><strong className="text-[#27251f]">Mes nefilmuojame dėl to, kad galime skraidyti.</strong> Kiekvienas skrydis turi istoriją, ritmą ir tikslą — parodyti erdvę taip, kaip jos dar nematėte.</p><p className="border-l-2 border-[#efc400] pl-4 italic text-[#27251f]">„Žiūrovas ne tik mato jūsų objektą. Jis nori jame būti.“</p></div></div><div className="lg:col-span-6 relative"><VideoComparisonSlider /></div></div></section>

    <section id="portfolio" className="py-20 md:py-28 bg-[#fcfbf7] border-y border-[#d9d4c8]"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10"><div><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Darbų portfolio</div><h2 className="font-display text-4xl sm:text-5xl font-bold tracking-tight leading-[1.03]">Mūsų darbai</h2></div><div className="flex flex-wrap gap-2">{[{id:'all',label:'Visi'},{id:'real-estate',label:'NT'},{id:'sports',label:'Sportas'},{id:'events',label:'Renginiai'},{id:'commercials',label:'Reklamos'}].map(tab => <button key={tab.id} onClick={() => setCategory(tab.id)} className={`px-4 py-2 rounded-full text-sm font-bold transition-colors ${category === tab.id ? 'bg-[#efc400] text-[#27251f]' : 'bg-[#ebe7de] text-[#6d6a61] hover:text-[#27251f]'}`}>{tab.label}</button>)}</div></div><div className="grid md:grid-cols-2 gap-6">{filtered.map((item, index) => <article key={item.id} onClick={() => setVideo(item)} className={`group cursor-pointer rounded-2xl overflow-hidden bg-[#f4f1e9] border border-[#d9d4c8] hover:-translate-y-1 transition-transform ${index === 0 ? 'md:col-span-2 md:grid md:grid-cols-[1.4fr_.6fr]' : ''}`}><div className={`${index === 0 ? 'aspect-[16/8]' : 'aspect-[16/10]'} relative overflow-hidden`}><img src={item.image} alt={item.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" /><div className="absolute inset-0 bg-gradient-to-t from-[#27251f]/80 via-transparent to-transparent" /><div className="absolute bottom-4 left-4 right-4 text-white"><div className="text-[10px] uppercase tracking-wider font-bold text-[#efc400]">{item.categoryLabel}</div><h3 className="font-display text-xl font-bold mt-1">{item.title}</h3></div><span className="absolute top-4 right-4 w-10 h-10 rounded-full bg-[#efc400] text-[#27251f] grid place-items-center opacity-0 group-hover:opacity-100 transition-opacity"><Play className="w-4 h-4 fill-current" /></span></div>{index === 0 && <div className="p-7 flex flex-col justify-between"><div><div className="text-sm text-[#6d6a61] mb-5">{item.location} • {item.year}</div><p className="text-[#6d6a61] leading-relaxed">{item.description}</p></div><div className="mt-8 text-sm font-bold flex items-center gap-2">Peržiūrėti projektą <ArrowUpRight className="w-4 h-4" /></div></div>}</article>)}</div><div className="mt-10 flex justify-center"><a href="/portfolio" className="inline-flex items-center gap-2 rounded-full bg-[#27251f] text-white px-6 py-3.5 font-bold hover:bg-[#3a382f] transition-colors">Žiūrėti visą portfolio <ArrowUpRight className="w-4 h-4" /></a></div></div></section>

    <section id="paslaugos" className="py-20 md:py-28"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="grid lg:grid-cols-[.75fr_1.25fr] gap-14"><div><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Ką darome</div><h2 className="font-display text-4xl sm:text-5xl font-bold leading-[1.02]">Nuo pirmos idėjos iki filmavimo</h2><p className="text-[#6d6a61] leading-relaxed mt-5 max-w-md">Aiškus procesas tiems, kurie nori gero rezultato, bet nenori patys tapti dronų ekspertais.</p></div><div className="divide-y divide-[#d9d4c8]">{serviceSteps.map(step => <div key={step.n} className="py-6 first:pt-0 last:pb-0 grid grid-cols-[55px_1fr] gap-5"><div className="font-display text-2xl font-bold text-[#9b7b00]">{step.n}</div><div><h3 className="font-display text-2xl font-bold">{step.title}</h3><p className="text-[#6d6a61] mt-2 leading-relaxed">{step.text}</p></div></div>)}</div></div></div></section>

    <ClientNeedsWalkthrough />

    <section id="atsiliepimai" className="py-20 md:py-28 paper-grid"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="flex items-end justify-between gap-6 mb-10"><div><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Atsiliepimai</div><h2 className="font-display text-4xl sm:text-5xl font-bold">Ką sako klientai</h2></div><Users className="hidden sm:block w-10 h-10 text-[#efc400]" /></div><div className="grid md:grid-cols-3 gap-5">{TESTIMONIALS.map(item => <blockquote key={item.author} className="rounded-2xl bg-[#fcfbf7] border border-[#d9d4c8] p-6"><div className="text-[#efc400] text-xl tracking-widest">★★★★★</div><p className="font-display text-xl leading-snug mt-5">„{item.quote}“</p><footer className="mt-7 text-sm text-[#6d6a61]"><strong className="text-[#27251f] block">{item.author}</strong>{item.type}</footer></blockquote>)}</div></div></section>

    <section id="technika" className="py-20 md:py-28 cream-panel border-y border-[#d9d4c8]"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10"><div><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Technika ir dronai</div><h2 className="font-display text-4xl sm:text-5xl font-bold tracking-tight">Parenkame ne pagal madą,<br />o pagal kadrą.</h2><p className="text-[#6d6a61] mt-4 max-w-xl">Skirtingas dronas reiškia skirtingą skrydžio būdą. Paspauskite kortelę ir sužinokite, kam jis skirtas.</p></div><div className="flex flex-wrap gap-2">{DRONE_SPECS.map(item => <button key={item.id} onClick={() => setDroneId(item.id)} className={`px-4 py-2 rounded-full text-xs font-bold transition-colors ${droneId === item.id ? 'bg-[#efc400] text-[#27251f]' : 'bg-[#fcfbf7] text-[#6d6a61] border border-[#d9d4c8] hover:border-[#9b7b00]'}`}>{item.name.replace('GELTONA ', '')}</button>)}</div></div><div className="rounded-3xl bg-[#fcfbf7] border border-[#d9d4c8] p-6 sm:p-9 shadow-sm"><div className="grid lg:grid-cols-[1.1fr_.9fr] gap-10 items-center"><div><div className="flex items-center gap-3 mb-4"><span className="rounded-full bg-[#efc400] text-[#27251f] text-xs font-bold px-3 py-1">{drone.highlightBadge}</span><span className="text-xs text-[#6d6a61]">{drone.class}</span></div><h3 className="font-display text-3xl font-bold">{drone.name}</h3><p className="text-[#6d6a61] leading-relaxed mt-4">{drone.description}</p><div className="grid sm:grid-cols-2 gap-5 mt-8 border-t border-[#d9d4c8] pt-6"><div><div className="text-[10px] uppercase tracking-wider text-[#9b7b00] font-bold">Maks. greitis</div><div className="font-bold mt-1">{drone.speed}</div></div><div><div className="text-[10px] uppercase tracking-wider text-[#9b7b00] font-bold">Skrydžio laikas</div><div className="font-bold mt-1">{drone.flightTime}</div></div><div className="sm:col-span-2"><div className="text-[10px] uppercase tracking-wider text-[#9b7b00] font-bold">Kamera</div><div className="font-bold mt-1">{drone.camera}</div></div></div><div className="mt-7 flex gap-3 text-sm text-[#6d6a61]"><ShieldCheck className="w-5 h-5 text-[#9b7b00] shrink-0" /><span>{drone.safety}</span></div></div><div className="rounded-2xl overflow-hidden"><img src={drone.image} alt={`${drone.name} FPV dronas`} className="w-full aspect-[4/3] object-cover" /></div></div></div></div></section>

    <section id="komanda" className="py-20 md:py-28 bg-[#fcfbf7] border-b border-[#d9d4c8]"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="grid lg:grid-cols-[.65fr_1.35fr] gap-14 mb-12"><div><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Žmonės už pulto</div><h2 className="font-display text-4xl sm:text-5xl font-bold leading-[1.02]">Ne vienas pilotas,<br />o visa komanda</h2></div><div><p className="text-xl text-[#6d6a61] leading-relaxed">Skirtingai nei dauguma pavienių filmuo​​tojų, galime pasiūlyti daugiau nei vieną pilotą vienam projektui. Tai reiškia, kad jūs gaunate daugiau kampų ir mažiau kompromisų didesniuose projektuose.</p><p className="text-[#6d6a61] leading-relaxed mt-4">Nutrūktgalviškiausi dronistai Lietuvoje</p></div></div><div className="max-w-5xl mx-auto grid sm:grid-cols-2 md:grid-cols-3 gap-4">{TEAM_MEMBERS.map(person => <article key={person.name} className="rounded-2xl border border-[#d9d4c8] bg-[#f4f1e9] overflow-hidden"><img src={person.image} alt={person.name} className="w-full aspect-[4/3] object-cover" /><div className="p-4"><h3 className="font-display text-xl font-bold">{person.name}</h3><div className="text-sm text-[#9b7b00] font-bold mt-1">{person.role}</div><p className="text-sm text-[#6d6a61] leading-relaxed mt-3">{person.bio}</p><div className="mt-4 pt-4 border-t border-[#d9d4c8] text-xs text-[#6d6a61]"><span className="font-bold text-[#27251f]">{person.callsign}</span> • {person.experience}</div></div></article>)}</div></div></section>

    <section id="kainodara" className="py-20 md:py-24 bg-[#efc400]"><div className="max-w-5xl mx-auto px-5 text-center"><div className="text-xs uppercase tracking-[.16em] font-bold text-[#27251f]/65 mb-4">Skaidri kainodara</div><h2 className="font-display text-4xl sm:text-6xl font-bold tracking-tight">Kaina priklauso nuo projekto.</h2><p className="text-lg text-[#27251f]/75 max-w-2xl mx-auto mt-5">Kelios valandos - lankstus valandinis tarifas. Visa darbo diena - fiksuota projekto kaina. Montažas, lokacija ir komandos dydis aptariami iš anksto. Kuro išlaidos į kainą neįskaičiuotos ir pridedamos pagal atstumą.</p><div className="grid md:grid-cols-2 gap-4 max-w-3xl mx-auto mt-9 text-left"><div className="rounded-2xl bg-[#fcfbf7]/75 p-5"><strong className="font-display text-xl">Valandinis 40eur/val</strong><p className="text-sm text-[#6d6a61] mt-2">Trumpam NT, interjero ar vieno epizodo filmavimui.</p></div><div className="rounded-2xl bg-[#27251f] text-white p-5"><strong className="font-display text-xl">Projekto kaina</strong><p className="text-sm text-white/65 mt-2">Visai dienai, renginiui, reklamai ar sudėtingesnei gamybai.</p></div></div><a href="#poreikiu-vedlys" className="inline-flex items-center gap-2 mt-9 rounded-full bg-[#27251f] text-white px-7 py-3.5 font-bold hover:bg-[#3a382f] transition-colors">Gauti pasiūlymą <ArrowRight className="w-4 h-4" /></a></div></section>

    <section id="duk" className="py-20 md:py-28"><div className="max-w-4xl mx-auto px-5"><div className="text-center mb-12"><div className="text-xs uppercase tracking-[.16em] font-bold text-[#9b7b00] mb-4">Dažniausi klausimai</div><h2 className="font-display text-4xl sm:text-5xl font-bold">D.U.K</h2></div><div className="space-y-3">{FAQ_ITEMS.map((item, index) => <div key={item.question} className="rounded-2xl border border-[#d9d4c8] bg-[#fcfbf7] overflow-hidden"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="w-full px-5 py-5 flex items-center justify-between gap-5 text-left font-display font-bold">{item.question}<ChevronDown className={`w-5 h-5 shrink-0 text-[#9b7b00] transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="px-5 pb-5 text-[#6d6a61] leading-relaxed">{item.answer}</p>}</div>)}</div></div></section>

    <section className="py-20 bg-[#27251f] text-white"><div className="max-w-4xl mx-auto px-5 text-center"><div className="text-xs uppercase tracking-[.16em] font-bold text-[#efc400] mb-4">Kaunas • visa Lietuva</div><h2 className="font-display text-4xl sm:text-6xl font-bold">Turite idėją?<br />Pakalbėkime gyvai.</h2><p className="text-white/65 text-lg max-w-xl mx-auto mt-5">Mielai atsakysime telefonu arba pakviesime į dirbtuves Kaune.</p><div className="flex flex-wrap justify-center gap-3 mt-8"><a href="tel:+37068575900" className="rounded-full bg-[#efc400] text-[#27251f] px-6 py-3.5 font-bold">+370 685 75900</a><a href="#poreikiu-vedlys" className="rounded-full border border-white/30 px-6 py-3.5 font-semibold">Užpildyti poreikių vedlį</a></div></div></section>

    <Footer /><VideoModal item={video} onClose={() => setVideo(null)} />
  </div>;
}
